# Generated by Django 6.0.6 on 2026-06-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
                ('categoria', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='images/')),
                ('quantidade', models.IntegerField(default=0)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_duracao_unidade', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
