# Generated by Django 6.0.5 on 2026-08-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='descricao',
            new_name='link_compra',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='quantidade',
            new_name='quantidade_minima',
        ),
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade_total',
            field=models.IntegerField(default=0),
        ),
    ]
