# Generated by Django 6.0.5 on 2026-09-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0004_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='previsao_fim_estoque',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
