# Generated by Django 6.0.5 on 2026-09-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0005_item_previsao_fim_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link_compra',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
