# Generated by Django 6.0.5 on 2026-09-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0006_alter_item_link_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link_compra',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
